title: John (Jack) Leniart # your name (or website title) here
logo: "/images/2022_Headshot1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  Portfolio highlighting projects I worked on while completing the Data Science Master's program at DePaul University.
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/jackleniart/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-8BK5LL2BE7 # your Google Analytics tracking ID here
